addons:
  # modules to install before running tests
  include:
    - contacts
    - stock
    - point_of_sale

  # modules to exclude from installation/testing
  exclude:
    - hw_proxy

  server_wide_modules:
    - web

repo_readme:
  addons:
    - pos_product_available
